const SET_TRACKS_ARRAY = "SET_TRACKS_ARRAY";
const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
const SET_RANDOM = "SET_RANDOM";
const SET_REPEAT = "SET_REPEAT";
const SET_PLAYING = "SET_PLAYING";

export {
  SET_TRACKS_ARRAY,
  SET_CURRENT_TRACK,
  SET_RANDOM,
  SET_REPEAT,
  SET_PLAYING,
};
