const SET_ALL_TRACKS = "GET_TRACKS";
const TRACK_ERROR = "TRACK_ERROR";
const UPDATE_LIKES = "UPDATE_LIKES";
const DELETE_TRACK = "DELETE_TRACK";
const SET_TRACKS_BY_USER = "SET_TRACKS_BY_USER";
const SET_FAV_TRACKS_BY_USER = "SET_FAV_TRACKS_BY_USER";

export {
  SET_ALL_TRACKS,
  TRACK_ERROR,
  UPDATE_LIKES,
  DELETE_TRACK,
  SET_TRACKS_BY_USER,
  SET_FAV_TRACKS_BY_USER,
};
