const SET_ALL_PLAYLISTS = "SET_ALL_PLAYLISTS";
const PLAYLIST_ERROR = "PLAYLIST_ERROR";
const UPDATE_PLAYLIST = "UPDATE_PLAYLIST";
const DELETE_PLAYLIST = "DELETE_PLAYLIST";
const SET_PLAYLISTS_BY_USER = "SET_PLAYLISTS_BY_USER";
const SET_CURRENT_PLAYLIST = "SET_CURRENT_PLAYLIST";
const SET_CURRENT_PLAYLIST_INFO = "SET_CURRENT_PLAYLIST_INFO";

export {
  SET_ALL_PLAYLISTS,
  PLAYLIST_ERROR,
  UPDATE_PLAYLIST,
  DELETE_PLAYLIST,
  SET_PLAYLISTS_BY_USER,
  SET_CURRENT_PLAYLIST,
  SET_CURRENT_PLAYLIST_INFO,
};
