const SET_TRACKS_INFO = "SET_TRACKS_INFO";
const SET_PLAYLISTS_INFO = "SET_PLAYLISTS_INFO";
const SET_ALBUMS_INFO = "SET_ALBUMS_INFO";
const SET_TRACKS_BY_USER = "SET_TRACKS_BY_USER";
const SET_PLAYLISTS_BY_USER = "SET_PLAYLISTS_BY_USER";
const SET_ALBUMS_BY_USER = "SET_ALBUMS_BY_USER";

export {
  SET_TRACKS_INFO,
  SET_PLAYLISTS_INFO,
  SET_ALBUMS_INFO,
  SET_TRACKS_BY_USER,
  SET_PLAYLISTS_BY_USER,
  SET_ALBUMS_BY_USER,
};
