const SET_TRACKS_INFO = "SET_TRACKS_INFO";
const SET_PLAYLISTS_INFO = "SET_PLAYLISTS_INFO";
const SET_ALBUMS_INFO = "SET_ALBUMS_INFO";

export { SET_TRACKS_INFO, SET_PLAYLISTS_INFO, SET_ALBUMS_INFO };
